inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/bundle
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
